//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
// 
#pragma warning disable 1591

namespace GeneralBiztalkHelper.riziv_inami.fgov.be.logging {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService_Riziv_Applications_BizTalk_LoggingSoap", Namespace="http://riziv-inami.fgov.be")]
    public partial class WebService_Riziv_Applications_BizTalk_Logging : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveUserLoggingOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveServiceLoggingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService_Riziv_Applications_BizTalk_Logging() {
            this.Url = global::GeneralBiztalkHelper.Properties.Settings.Default.GeneralBiztalkHelper_riziv_inami_fgov_be_logging_WebService_BizTalk_DashBoard;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveUserLoggingCompletedEventHandler SaveUserLoggingCompleted;
        
        /// <remarks/>
        public event SaveServiceLoggingCompletedEventHandler SaveServiceLoggingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://riziv-inami.fgov.be/WebService_Riziv_Applications_BizTalk_Logging/SaveUser" +
            "Logging", RequestNamespace="http://riziv-inami.fgov.be", ResponseNamespace="http://riziv-inami.fgov.be", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("UserLoggingResult")]
        public SaveUserLoggingResponseUserLoggingResult SaveUserLogging([System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk_DashBoard.Schemas.UserLogging")] UserLogInfo UserLogInfo) {
            object[] results = this.Invoke("SaveUserLogging", new object[] {
                        UserLogInfo});
            return ((SaveUserLoggingResponseUserLoggingResult)(results[0]));
        }
        
        /// <remarks/>
        public void SaveUserLoggingAsync(UserLogInfo UserLogInfo) {
            this.SaveUserLoggingAsync(UserLogInfo, null);
        }
        
        /// <remarks/>
        public void SaveUserLoggingAsync(UserLogInfo UserLogInfo, object userState) {
            if ((this.SaveUserLoggingOperationCompleted == null)) {
                this.SaveUserLoggingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveUserLoggingOperationCompleted);
            }
            this.InvokeAsync("SaveUserLogging", new object[] {
                        UserLogInfo}, this.SaveUserLoggingOperationCompleted, userState);
        }
        
        private void OnSaveUserLoggingOperationCompleted(object arg) {
            if ((this.SaveUserLoggingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveUserLoggingCompleted(this, new SaveUserLoggingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://riziv-inami.fgov.be/WebService_Riziv_Applications_BizTalk_Logging/SaveServ" +
            "iceLogging", RequestNamespace="http://riziv-inami.fgov.be", ResponseNamespace="http://riziv-inami.fgov.be", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("part")]
        public string SaveServiceLogging([System.Xml.Serialization.XmlElementAttribute(Namespace="http://BizTalk_DashBoard.Schemas.ServiceLogInfo")] LogInfo LogInfo) {
            object[] results = this.Invoke("SaveServiceLogging", new object[] {
                        LogInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveServiceLoggingAsync(LogInfo LogInfo) {
            this.SaveServiceLoggingAsync(LogInfo, null);
        }
        
        /// <remarks/>
        public void SaveServiceLoggingAsync(LogInfo LogInfo, object userState) {
            if ((this.SaveServiceLoggingOperationCompleted == null)) {
                this.SaveServiceLoggingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveServiceLoggingOperationCompleted);
            }
            this.InvokeAsync("SaveServiceLogging", new object[] {
                        LogInfo}, this.SaveServiceLoggingOperationCompleted, userState);
        }
        
        private void OnSaveServiceLoggingOperationCompleted(object arg) {
            if ((this.SaveServiceLoggingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveServiceLoggingCompleted(this, new SaveServiceLoggingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk_DashBoard.Schemas.UserLogging")]
    public partial class UserLogInfo {
        
        private string idField;
        
        private string userIdField;
        
        private string nationalRegistryNbField;
        
        private string applicationField;
        
        private string statusField;
        
        private string requestField;
        
        private string requestStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NationalRegistryNb {
            get {
                return this.nationalRegistryNbField;
            }
            set {
                this.nationalRegistryNbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RequestString {
            get {
                return this.requestStringField;
            }
            set {
                this.requestStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://riziv-inami.fgov.be")]
    public partial class SaveUserLoggingResponseUserLoggingResult {
        
        private object successField;
        
        /// <remarks/>
        public object Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BizTalk_DashBoard.Schemas.ServiceLogInfo")]
    public partial class LogInfo {
        
        private string serviceLogIDField;
        
        private string applicationNameField;
        
        private string serviceNameField;
        
        private string serviceTypeField;
        
        private string serviceStateField;
        
        private string serviceFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceLogID {
            get {
                return this.serviceLogIDField;
            }
            set {
                this.serviceLogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceState {
            get {
                return this.serviceStateField;
            }
            set {
                this.serviceStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServiceFileName {
            get {
                return this.serviceFileNameField;
            }
            set {
                this.serviceFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void SaveUserLoggingCompletedEventHandler(object sender, SaveUserLoggingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveUserLoggingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveUserLoggingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveUserLoggingResponseUserLoggingResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveUserLoggingResponseUserLoggingResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void SaveServiceLoggingCompletedEventHandler(object sender, SaveServiceLoggingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveServiceLoggingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveServiceLoggingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591