//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VisualStudio.BizTalkProject.Generators, Version 4.0.30319.1.
// 
namespace MedegaImport.GuardsImportService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GuardsImportServiceSoap", Namespace="http://riziv.fgov.be/GuardsImportService")]
    [Microsoft.XLANGs.BaseTypes.WebServiceUrlAttribute("http://iisd-tst/szvmedegaservice/GuardsImportService.asmx")]
    public partial class GuardsImportService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public GuardsImportService() {
            this.Url = "http://iisd-tst/szvmedegaservice/GuardsImportService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://riziv.fgov.be/GuardsImportService/ImportMedegaXml", RequestNamespace="http://riziv.fgov.be/GuardsImportService", ResponseNamespace="http://riziv.fgov.be/GuardsImportService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid ImportMedegaXml(System.Xml.XmlNode medegaXml, string xmlFileName) {
            object[] results = this.Invoke("ImportMedegaXml", new object[] {
                        medegaXml,
                        xmlFileName});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportMedegaXml(System.Xml.XmlNode medegaXml, string xmlFileName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportMedegaXml", new object[] {
                        medegaXml,
                        xmlFileName}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Guid EndImportMedegaXml(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://riziv.fgov.be/GuardsImportService/GetImportMedegaXmlResults", RequestNamespace="http://riziv.fgov.be/GuardsImportService", ResponseNamespace="http://riziv.fgov.be/GuardsImportService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object GetImportMedegaXmlResults(System.Guid trackingId) {
            object[] results = this.Invoke("GetImportMedegaXmlResults", new object[] {
                        trackingId});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetImportMedegaXmlResults(System.Guid trackingId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetImportMedegaXmlResults", new object[] {
                        trackingId}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndGetImportMedegaXmlResults(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://riziv.fgov.be/GuardsImportService/ImportMedegaGuard", RequestNamespace="http://riziv.fgov.be/GuardsImportService", ResponseNamespace="http://riziv.fgov.be/GuardsImportService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ImportMedegaGuardResult ImportMedegaGuard(ImportMedegaGuardRequest medegaGuardRequest) {
            object[] results = this.Invoke("ImportMedegaGuard", new object[] {
                        medegaGuardRequest});
            return ((ImportMedegaGuardResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginImportMedegaGuard(ImportMedegaGuardRequest medegaGuardRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ImportMedegaGuard", new object[] {
                        medegaGuardRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ImportMedegaGuardResult EndImportMedegaGuard(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ImportMedegaGuardResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://riziv.fgov.be/GuardsImportService/test", RequestNamespace="http://riziv.fgov.be/GuardsImportService", ResponseNamespace="http://riziv.fgov.be/GuardsImportService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool test() {
            object[] results = this.Invoke("test", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begintest(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("test", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endtest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://riziv.fgov.be/GuardsImportService")]
    public partial class ImportMedegaGuardResult {
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public long PeriodId;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public long FileId;
        
        /// <remarks/>
        public GuardStates GuardStatus;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string FailureDescription;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string FailureCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://riziv.fgov.be/GuardsImportService")]
    public enum GuardStates {
        
        /// <remarks/>
        Imported,
        
        /// <remarks/>
        Overlapping,
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Paid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://riziv.fgov.be/GuardsImportService")]
    public partial class ImportMedegaGuardRequest {
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public long PeriodId;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public long FileId;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public long ImportXmlId;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string RizivNumber;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string LastName;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string FirstName;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string BankAccountNumber;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string GuardDate;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string GuardStartTime;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string GuardEndTime;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public int ZoneId;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string ZoneName;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string GeographicEntityName;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string NisCode;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string ZipCode;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string ResponsableRizivNumber;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string ResponsableLastName;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string ResponsableFirstName;
        
        /// <remarks/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string ValidationError;
    }
}
